### ISSUE TITLE
New TUM options ideas

### ISSUE THREAD

**Issue by Archer30** [Archer30/Third-Upgrade-Mod#11]
Some players reported to me that the Pandora's Box alternation (by Elfbi's script) is not expected. They wish to play with the original Pandora. I added Elfbi's script dependency on the object replacement option of WoG Scripts, it should somehow help with this issue. But a better fix is:

> **Make a New Pandora's Box option on the first page of WoG option menu.**

Is this a good idea?

A concern is that for the current WoG option menu, there is not much space for more options. It is better to think further about which option might be added in the future.

Some ideas:
**Mysterious Cave**. Allows this object to be turned on/off.
**Rebalance Eighth Monsters**. Rebalance the 8th monster of all the factions, mainly on stats. The idea is to stop players from complaining hey yo what the heck Templar from Castle is so much stronger than Triton from Conflux.

Any idea, comment?

**Comment by VMaiko1634** [comment]
The idea of Pandora box sounds a bit unnecessary to me, but if there are people who don't like it then there are reasons to create an option to disable it, the same with Mysterious Cave, It's up to you to implement them or not. The last idea is not clear, nor consistent, and could bring more complaints than solutions, because many people will want stronger or weaker units that make 8th monsters worth having. This last idea will not lead us to a desired progress. The only real solution is to be able to implement alternative dwellings as in ToW.

**Comment by Archer30** [comment]
`The only real solution is to be able to implement alternative dwellings as in ToW.`

This can be done through scripting. 
In fact, ToW for ERA did quite well with only the HD mod dialogue supporting missing, but it can now be fixed.
The only issue here is, there is no third upgrade ToW creature to make this a valid option.
